import React, { FC } from 'react';

const MagazinesPage: FC = () => {
    return (
        <div className={"container"} >
            <h1>Magazines Page</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto blanditiis doloremque expedita explicabo optio quisquam voluptas. Consequuntur distinctio nihil odit perspiciatis voluptate. Culpa cupiditate dolorem ducimus incidunt inventore labore minima!</p>

        </div>
    );
};

export default MagazinesPage;